#Note: code generated by ChatGPT

import time
from src.sorting import (
    bubble_sort,
    selection_sort,
    insertion_sort,
    merge_sort,
    quick_sort,
)


def take_time_for_algorithm(samples_array, sorting_function):
    """
    Measures execution time of a sorting function using multiple samples.
    Returns the median execution time.
    """

    times = []

    for sample in samples_array:
        start = time.perf_counter()
        sorting_function(sample.copy())
        end = time.perf_counter()

        times.append(end - start)

    times.sort()
    return times[len(times) // 2]  # median time


def take_times(size, samples_by_size, generator_function):
    """
    Generates samples using the provided generator function
    and measures execution time for all sorting algorithms.
    """

    samples = []

    for _ in range(samples_by_size):
        samples.append(generator_function(size))

    return [
        take_time_for_algorithm(samples, bubble_sort),
        take_time_for_algorithm(samples, selection_sort),
        take_time_for_algorithm(samples, insertion_sort),
        take_time_for_algorithm(samples, merge_sort),
        take_time_for_algorithm(samples, quick_sort),
    ]


def take_execution_time(minimum_size, maximum_size, step, samples_by_size, generator_function):
    """
    Runs performance experiments for input sizes in the given range
    using the specified data generator function.

    Returns:
        A list of rows in the format:
        [size, bubble_time, selectio  n_time, insertion_time, merge_time, quick_time]
    """

    table = []

    for size in range(minimum_size, maximum_size + 1, step):
        print(f"Processing size: {size}")

        row = [size]
        times = take_times(size, samples_by_size, generator_function)
        table.append(row + times)

    return table