#Note: data generated by ChatGPT 

from src.execution_time_gathering import take_execution_time
from src.plot_results import plot_execution_times
from src.data_generator import (
    get_random_list,
    get_sorted_list,
    get_reverse_sorted_list,
    get_nearly_sorted_list,
)

if __name__ == "__main__":

    print("\n===== RANDOM DATA =====")
    random_results = take_execution_time(100, 1000, 100, 5, get_random_list)
    plot_execution_times(random_results)

    print("\n===== SORTED DATA =====")
    sorted_results = take_execution_time(100, 1000, 100, 5, get_sorted_list)
    plot_execution_times(sorted_results)

    print("\n===== REVERSE SORTED DATA =====")
    reverse_results = take_execution_time(100, 1000, 100, 5, get_reverse_sorted_list)
    plot_execution_times(reverse_results)

    print("\n===== NEARLY SORTED DATA =====")
    nearly_results = take_execution_time(100, 1000, 100, 5, get_nearly_sorted_list)
    plot_execution_times(nearly_results)