#Note: code generated by ChatGPT


def bubble_sort(arr):
    """
    Bubble Sort

    Best Case:    O(n)        when its already organized
    Average Case: O(n^2)
    Worst Case:   O(n^2)
    Space:        O(1)
    Stable:       Yes
    """
    n = len(arr)
    arr = arr.copy()  # extra memory used only for copying input

    for i in range(n):  # outer loop runs n times -> contributes to O(n)
        swapped = False
        for j in range(0, n - i - 1):  # inner loop runs up to n times
            # nested loops (n * n) -> O(n^2) average and worst case
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]  # constant time swap
                swapped = True
        if not swapped:
            break  # early stop when already sorted -> best case becomes O(n)

    return arr


def selection_sort(arr):
    """
    Selection Sort

    Best Case:    O(n^2)
    Average Case: O(n^2)
    Worst Case:   O(n^2)
    Space:        O(1)
    Stable:       No
    """
    arr = arr.copy()
    n = len(arr)

    for i in range(n):  # outer loop runs n times
        min_index = i
        for j in range(i + 1, n):  # inner loop scans remaining elements
            # nested loops always execute fully -> always O(n^2)
            if arr[j] < arr[min_index]:
                min_index = j
        arr[i], arr[min_index] = arr[min_index], arr[i]  # constant time swap

    return arr


def insertion_sort(arr):
    """
    Insertion Sort

    Best Case:    O(n)
    Average Case: O(n^2)
    Worst Case:   O(n^2)
    Space:        O(1)
    Stable:       Yes
    """
    arr = arr.copy()

    for i in range(1, len(arr)):  # outer loop runs n times
        key = arr[i]
        j = i - 1

        while j >= 0 and arr[j] > key:  
            # shifting elements backwards can take up to n steps
            # inside outer loop -> O(n^2) worst and average
            arr[j + 1] = arr[j]
            j -= 1

        arr[j + 1] = key  # insertion operation

        # if array already sorted the while loop barely runs
        # making the algorithm O(n) in best case

    return arr


def merge_sort(arr):
    """
    Merge Sort

    Best Case:    O(n log n)
    Average Case: O(n log n)
    Worst Case:   O(n log n)
    Space:        O(n)
    Stable:       Yes
    """

    if len(arr) <= 1:
        return arr  # base case for recursion

    mid = len(arr) // 2
    left = merge_sort(arr[:mid])   # recursive division -> creates log n levels
    right = merge_sort(arr[mid:])  # each level splits the problem in half

    return _merge(left, right)  
    # merging processes all n elements per level -> n work * log n levels = O(n log n)


def _merge(left, right):
    result = []
    i = j = 0

    while i < len(left) and j < len(right):
        # compares elements from both halves
        # each element processed once -> contributes to O(n)
        if left[i] <= right[j]:
            result.append(left[i])  # append is constant time
            i += 1
        else:
            result.append(right[j])
            j += 1

    result.extend(left[i:])   # adds remaining elements -> still linear
    result.extend(right[j:])  # contributes to total O(n) merging cost
    return result


def quick_sort(arr):
    """
    Quick Sort

    Best Case:    O(n log n)
    Average Case: O(n log n)
    Worst Case:   O(n^2)      when the pivot point is quite bad
    Space:        O(log n)    using recursion 
    Stable:       No
    """

    if len(arr) <= 1:
        return arr  # recursion base case

    pivot = arr[len(arr) // 2]  # pivot selection

    left = [x for x in arr if x < pivot]   
    # list comprehension scans entire array -> O(n)

    middle = [x for x in arr if x == pivot]  
    # another full scan -> O(n)

    right = [x for x in arr if x > pivot]  
    # another full scan -> O(n)

    # recursive calls split the array roughly in half
    # producing log n recursion depth in average case
    return quick_sort(left) + middle + quick_sort(right)
    # n work per level * log n levels -> O(n log n)
    # if pivot splits poorly each time -> depth n -> O(n^2)


__all__ = [
    "bubble_sort",
    "selection_sort",
    "insertion_sort",
    "merge_sort",
    "quick_sort",
]
