#Note: code generated by ChatGPT


def bubble_sort(arr):
    """
    Bubble Sort

    Best Case:    O(n)        when its already organized
    Average Case: O(n^2)
    Worst Case:   O(n^2)
    Space:        O(1)
    Stable:       Yes
    """
    n = len(arr)
    arr = arr.copy()

    for i in range(n):
        swapped = False
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
                swapped = True
        if not swapped:
            break

    return arr


def selection_sort(arr):
    """
    Selection Sort

    Best Case:    O(n^2)
    Average Case: O(n^2)
    Worst Case:   O(n^2)
    Space:        O(1)
    Stable:       No
    """
    arr = arr.copy()
    n = len(arr)

    for i in range(n):
        min_index = i
        for j in range(i + 1, n):
            if arr[j] < arr[min_index]:
                min_index = j
        arr[i], arr[min_index] = arr[min_index], arr[i]

    return arr


def insertion_sort(arr):
    """
    Insertion Sort

    Best Case:    O(n)
    Average Case: O(n^2)
    Worst Case:   O(n^2)
    Space:        O(1)
    Stable:       Yes
    """
    arr = arr.copy()

    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1

        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1

        arr[j + 1] = key

    return arr

def merge_sort(arr):
    """
    Merge Sort

    Best Case:    O(n log n)
    Average Case: O(n log n)
    Worst Case:   O(n log n)
    Space:        O(n)
    Stable:       Yes
    """

    if len(arr) <= 1:
        return arr

    mid = len(arr) // 2
    left = merge_sort(arr[:mid])
    right = merge_sort(arr[mid:])

    return _merge(left, right)


def _merge(left, right):
    result = []
    i = j = 0

    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1

    result.extend(left[i:])
    result.extend(right[j:])
    return result


def quick_sort(arr):
    """
    Quick Sort

    Best Case:    O(n log n)
    Average Case: O(n log n)
    Worst Case:   O(n^2)      when the pivot point is quite bad
    Space:        O(log n)    using recursion 
    Stable:       No
    """

    if len(arr) <= 1:
        return arr

    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    return quick_sort(left) + middle + quick_sort(right)


__all__ = [
    "bubble_sort",
    "selection_sort",
    "insertion_sort",
    "merge_sort",
    "quick_sort",
]